### ISSUE TITLE
Reporte del diseño 

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-companion-ai#2]
[Reporte de practica 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-companion-ai/files/14724494/Reporte.de.practica.1.pdf)

Evelyn Santiago Victoria
Vanessa Cruz Ortiz
Nancy Olivera Santiago

**Comment by IrvinSanchez-dev** [comment]
La calificacion obtenida mediante la rubrica es de 17%

** Puntos a aclarar.
- En el objetivo de la practica no contiene todo, solo es una pequeña linea y le hace falta mas informacion.
- En la descripcion de la practica y el procedimiento no contiene la informacion que indique que metodos fueron implementados.
- La lista de figuras es minima ya que solo contiene 8 figuras.

**Comment by josealfredo79** [comment]
El diseño de la libreria es para su proyecto por favor.. @Nancy-0714 aqui solo se diseña,..no se implementa...
